"""R-audit: the singular 3-layer perovskite stress device.

This device is NOT a working solar cell (Voc=nan, Jsc~0 even when its sweep
"converges"). It is a deliberately rank-deficient Jacobian stress test
(dense kappa ~ 4e45) used to exercise the truncated-SVD (lstsq) fallback.
Its behavior is fragile: with the raw default spectrum the sweep converges
to ~1e-8 via fallback on every bias, but with the normalized 1000 W/m^2
spectrum the extra drive diverges biases beyond the fallback recovery radius.

These two facts are pinned here so the behavior cannot drift silently (the
archived solver_fallback.json record is regenerated by
validation/solver_fallback.py and must match).
"""

import jax.numpy as jnp
import pytest

import driftjax as dj
from driftjax.science.spectrum import spectrum as _spectrum


def _three_layer():
    mt = dj.material(Eg=1.6, Chi=3.9, eps=20.0, Nc=1e18, Nv=1e18, mn=100.0, mp=100.0, A=2e4)
    mat = dj.material(Eg=1.4, Chi=3.0, eps=10.0, Nc=1e18, Nv=1e18, mn=130.0, mp=160.0, A=2e4)
    return dj.Device(
        n_points=15,
        layers=[(2e-5, mt, 1e18), (6e-5, mat, -1e18), (2e-5, mat, 1e18)],
        Snl=1e7,
        Snr=0.0,
        Spl=0.0,
        Spr=1e7,
    )


@pytest.mark.slow  # reproduces the archived solver_fallback.json record
@pytest.mark.slow
def test_three_layer_converges_with_default_spectrum():
    """Archived outcome: fallback fires on all 5 biases, residual ~1e-8."""
    s = dj.simulate(_three_layer(), dj.Sweep(n_steps=5, vmax=1.0), solver=dj.Newton(backend="auto"))
    assert bool(s.converged), (
        f"expected convergence with default spectrum, max|F|={float(s.max_residual)}"
    )
    assert all(bool(x) for x in s.fallback_used), s.fallback_used
    assert float(s.max_residual) < 1e-6, float(s.max_residual)


@pytest.mark.slow
@pytest.mark.slow
def test_three_layer_diverges_with_normalized_spectrum():
    """The normalized 1000 W/m^2 spectrum pushes the singular device past the
    fallback recovery radius -> non-convergence. This pins the fragility, not a
    desired behavior: the device is a stress test, not a physical cell."""
    with pytest.warns(UserWarning, match="did not converge"):
        s = dj.simulate(_three_layer(), dj.Sweep(n_steps=5, vmax=1.0), ls=_spectrum(), solver=dj.Newton(backend="auto"))
    assert not bool(s.converged)
    assert float(s.max_residual) > 1.0
    # even the "converged" variant is not a physical cell
    assert float(s.voc) != float(s.voc) or not bool(jnp.isfinite(s.voc)), "Voc must be nan"


@pytest.mark.slow
@pytest.mark.slow
def test_three_layer_is_not_a_physical_cell():
    """With the default (converging) spectrum, Jsc is ~0 and Voc=nan: the
    n-p-n structure with an n+ layer at the hole contact has no hole path."""
    s = dj.simulate(_three_layer(), dj.Sweep(n_steps=5, vmax=1.0), solver=dj.Newton(backend="auto"))
    assert abs(float(s.jsc) * 1e4) < 1.0, f"Jsc should be ~0, got {float(s.jsc) * 1e4:.2f} A/m2"
    assert not bool(jnp.isfinite(s.voc)), "Voc should be nan for this non-collecting structure"
